version: '3.8'

services:
  backend:
    build: ./backend
    container_name: watch-sec-backend
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=mysql+aiomysql://root:rootpassword@db_sql:3306/watchsec
      - MONGO_URL=mongodb://mongo:27017
      - HOST=0.0.0.0
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - db_sql
      - mongo
      - redis
    volumes:
      - ./backend/storage:/app/storage

  frontend:
    build:
      context: ../watch-sec-frontend
      args:
        VITE_API_URL: https://api.monitorix.co.in
    container_name: watch-sec-frontend
    ports:
      - "8080:80"
    depends_on:
      - backend

  celery:
    build: ./backend
    container_name: watch-sec-celery
    command: celery -A app.worker.celery_app worker --loglevel=info
    environment:
      - DATABASE_URL=mysql+aiomysql://root:rootpassword@db_sql:3306/watchsec
      - MONGO_URL=mongodb://mongo:27017
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - backend
      - redis
      - db_sql
      - mongo
    volumes:
      - ./backend/storage:/app/storage

  redis:
    image: redis:7
    container_name: watch-sec-redis
    ports:
      - "6379:6379"

  db_sql:
    image: mysql:8.0
    container_name: watch-sec-sql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: watchsec
    ports:
      - "3307:3306" # Mapped to 3307 to avoid conflict with local MySQL
    volumes:
      - sql_data:/var/lib/mysql

  mongo:
    image: mongo:6.0
    container_name: watch-sec-mongo
    ports:
      - "27018:27017" # Mapped to 27018 to avoid conflict with local Mongo
    volumes:
      - mongo_data:/data/db

volumes:
  sql_data:
  mongo_data:
