[phases.setup]
nixPkgs = ["python310", "gcc", "mysql-client"]

[phases.build]
cmds = ["pip install -r requirements.txt"]

[start]
cmd = "python -m app.scripts.seed && uvicorn app.main:app --host 0.0.0.0 --port $PORT"
